### PR TITLE
Associations for  Models 

### PR DESCRIPTION
**Pull request by ghost**
Created and tested Associations for all models. (hendrik and jason)

### CODE REVIEW

**Comment by Jason076983** [comment]
Howzit gents, all good from my side.

**Review by JasonOCodes — APPROVED** [review]
All good from my side gents

**Review by Jonocmore — APPROVED** [review]
Awesome stuff! Thanks guys, let's keep pushing. Looking forward to the session this evening.

**Review by PercyManenzhe — COMMENTED** [review]
Thanx i can see that you were all pushing....great team work

**Pull request merged**
